os: linux

language: node_js

node_js:
  - '14'
  - '12'
  - '10'
  - 'node'

install: npm install

script:
  - npm run lint
  - npm run test:ci

after_success:
  - codecov --token="$CODECOV_TOKEN"

branches:
  only:
    - main
    - "/v\\d-beta/"
    - "/^v\\d+\\.\\d+\\.\\d+.*$/"
